#  NumPy Classroom Exercise 

 
**Rules:** Use only **NumPy** (`import numpy as np`). Avoid Python loops unless asked.


In [34]:
# Setup
import numpy as np


**Task 1.1** Create:
- `A` with shape `(3, 4)` of type `float64` containing values `0..11`.
- `B` as a `(4, 1)` column vector of type `int32` containing values `1..4`.
- Without copying, create `A_view` selecting the **last two columns** of `A`. Prove modifying `A_view` also changes `A`.

**Task 1.2** Convert `B` to `float64` **without** changing `B` in place, and explain why `A @ B` fails or succeeds.

In [35]:
# === Your work: 1.1 & 1.2 ===
# Create A, B, A_view as described; then demonstrate the view behavior and try A @ B.



In [36]:
# Task 1.1
A = np.arange(12, dtype=np.float64).reshape(3, 4)
B = np.arange(1, 5, dtype=np.int32).reshape(4, 1)
A_view = A[:, 2:]  # last two columns, view not copy
A_view[:] = -1
print("A after modifying A_view:\n", A)

# Task 1.2
B_float = B.astype(np.float64)
result = A @ B_float
print("A @ B_float:\n", result)
explanation_12 = """
A @ B succeeds because A is (3,4) and B is (4,1), so matrix multiplication is valid and results in shape (3,1).
"""
print(explanation_12)

A after modifying A_view:
 [[ 0.  1. -1. -1.]
 [ 4.  5. -1. -1.]
 [ 8.  9. -1. -1.]]
A @ B_float:
 [[-5.]
 [ 7.]
 [19.]]

A @ B succeeds because A is (3,4) and B is (4,1), so matrix multiplication is valid and results in shape (3,1).



`X = np.arange(1, 13).reshape(3, 4)`, `w = np.array([1, -1, 1, -1])`

**Task 2.1** Multiply each column of X by the matching weight in w and then add across the row.
The result should be a 1-D array with 3 values (one for each row).
Do this without using any loops.

**Task 2.2** Standardize `X` **column‑wise** to zero mean/unit var using broadcasting. Verify means/stds.
"Standardize” means:

Subtract the mean of each column,

Then divide by that column’s standard deviation.

This makes each column have mean ≈ 0 and standard deviation ≈ 1.

**Task 2.3** Explain why `X + np.array([1, 2])` errors, but `X + np.array([[1],[2],[3]])` works.

In [37]:
# === Your work: 2.1–2.3 ===
X = np.arange(1, 13).reshape(3, 4)
w = np.array([1, -1, 1, -1])

# 2.1

# 2.2

# 2.3 (brief note in a string variable)
reasoning_23 = """
"""


In [38]:
# 2.1
weighted_sum = (X * w).sum(axis=1)
print("Task 2.1 result:", weighted_sum)

# 2.2
X_mean = X.mean(axis=0)
X_std = X.std(axis=0)
X_standardized = (X - X_mean) / X_std
print("Task 2.2 standardized X:\n", X_standardized)
print("Means (should be ~0):", X_standardized.mean(axis=0))
print("Stds (should be ~1):", X_standardized.std(axis=0))

# 2.3
reasoning_23 = """
X + np.array([1, 2]) errors because their shapes are not compatible for broadcasting: (3,4) vs (2,).
X + np.array([[1],[2],[3]]) works because (3,1) broadcasts to (3,4) along columns.
"""
print(reasoning_23)

Task 2.1 result: [-2 -2 -2]
Task 2.2 standardized X:
 [[-1.22474487 -1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487  1.22474487]]
Means (should be ~0): [0. 0. 0. 0.]
Stds (should be ~1): [1. 1. 1. 1.]

X + np.array([1, 2]) errors because their shapes are not compatible for broadcasting: (3,4) vs (2,).
X + np.array([[1],[2],[3]]) works because (3,1) broadcasts to (3,4) along columns.




Let `rng = np.random.default_rng(0)` and `Z = rng.normal(0, 1, (5, 6))`.

`Z` becomes a **5×6 matrix** filled with random numbers drawn from the standard normal distribution (mean 0, std 1).  


**Task 3.1** Count how many rows have **≥ 3** strictly positive entries (no loops).

**Task 3.2** Replace negatives with their squares; keep non‑negatives unchanged (vectorized).

In [ ]:
# === Your work: 3.1–3.3 ===
rng = np.random.default_rng(0)
Z = rng.normal(loc=0, scale=1, size=(5, 6))

# 3.1
num_rows_with_3pos = (Z > 0).sum(axis=1) >= 3
count_3pos_rows = num_rows_with_3pos.sum()
print("Rows with ≥3 strictly positive entries:", count_3pos_rows)
# 3.2
Z_transformed = np.where(Z < 0, Z**2, Z)
print("Z with negatives squared:\n", Z_transformed)


Create `Y = np.arange(1, 13).reshape(3, 4)`.

**Task 4.1** Use **basic slicing** to extract columns 1..2 and set them to `-99`. Show `Y` changed.


In [42]:
# === Your work: 4.1–4.2 ===
Y = np.arange(1, 13).reshape(3, 4)

# 4.1
Y[:, 1:3] = -99
print("Y after setting columns 1 and 2 to -99:\n", Y)




Y after setting columns 1 and 2 to -99:
 [[  1 -99 -99   4]
 [  5 -99 -99   8]
 [  9 -99 -99  12]]


Define `a=b=(2,000,000)` random normals.

**Task 5.1** Compute cosine similarity once using **pure Python loops** and once using **NumPy**; time both (use `%timeit`/`%%timeit` in Jupyter).

In [ ]:
# === Your work: 7.1 ===
rng = np.random.default_rng(0)
a = rng.normal(size=2_000_000)
b = rng.normal(size=2_000_000)

# Pure Python loops (sketch; be careful—this will be slow)
# dot = 0.0
# for i in range(len(a)):
#     dot += float(a[i]) * float(b[i])
# cos_loop = dot / (np.sqrt((a*a).sum()) * np.sqrt((b*b).sum()))

# NumPy vectorized
# %timeit a.dot(b) / (np.linalg.norm(a)*np.linalg.norm(b))

def cosine_similarity_loop(a, b):
    dot = 0.0
    norm_a = 0.0
    norm_b = 0.0
    for i in range(len(a)):
        ai = float(a[i])
        bi = float(b[i])
        dot += ai * bi
        norm_a += ai * ai
        norm_b += bi * bi
    return dot / (norm_a**0.5 * norm_b**0.5)

# Time pure Python loop
%timeit cosine_similarity_loop(a, b)

# NumPy vectorized
%timeit a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))

195 ms ± 2.12 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
884 μs ± 96 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
